// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCoGvfjTUL-MGblGs-zypk8CF3fQjkEXQ',
    appId: '1:2832176053:web:a3e46dc47e98eff86efffc',
    messagingSenderId: '2832176053',
    projectId: 'youtube-clone-x',
    authDomain: 'clone-x-6068f.firebaseapp.com',
    storageBucket: 'youtube-clone-x.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGdJYk0vJAN7ZRrI8Ekv5cCEeFy5Eo1Y',
    appId: '1:2832176053:android:43a320d06333b4316efffc',
    messagingSenderId: '2832176053',
    projectId: 'youtube-clone-x',
    storageBucket: 'youtube-clone-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA4KplZylkRUQ6f_tkPo8qheVDBEl3wYI',
    appId: '1:2832176053:ios:86e03709cd77d3236efffc',
    messagingSenderId: '2832176053',
    projectId: 'youtube-clone-x',
    storageBucket: 'youtube-clone-x.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA4KplZylkRUQ6f_tkPo8qheVDBEl3wYI',
    appId: '1:2832176053:ios:86e03709cd77d3236efffc',
    messagingSenderId: '2832176053',
    projectId: 'youtube-clone-x',
    storageBucket: 'youtube-clone-x.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCoGvfjTUL-MGblGs-zypk8CF3fQjkEXQ',
    appId: '1:2832176053:web:63387630687bd34d6efffc',
    messagingSenderId: '2832176053',
    projectId: 'youtube-clone-x',
    authDomain: 'clone-x-6068f.firebaseapp.com',
    storageBucket: 'youtube-clone-x.firebasestorage.app',
  );
}
