// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-o1qou5hqRDW4fCi_8B_kh9NzL6hi7E',
    appId: '1:130331150229:web:2d2b40fce4b3afa3dcd89c',
    messagingSenderId: '130331150229',
    projectId: 'clone-bd0fe',
    authDomain: 'clone-bd0fe.firebaseapp.com',
    storageBucket: 'clone-bd0fe.firebasestorage.app',
    measurementId: 'G-62NRJ45WGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBev68Sh7FyogIUfLeI1rd884_Ur35AdaE',
    appId: '1:130331150229:android:e2834beec28ce140dcd89c',
    messagingSenderId: '130331150229',
    projectId: 'clone-bd0fe',
    storageBucket: 'clone-bd0fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR0OiWucXersIxA37dfBtwJjad_BnaFUI',
    appId: '1:130331150229:ios:1cfe1435a60edc2ddcd89c',
    messagingSenderId: '130331150229',
    projectId: 'clone-bd0fe',
    storageBucket: 'clone-bd0fe.firebasestorage.app',
    iosBundleId: 'com.example.youtubeClone',
  );
}
